/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import loadingScene from "./loadingScene"
import MyGameScene from "./Game/MyGameScene"
import Fruit from "./Game/Fruit"
import Juice from "./Game/Juice"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="loadingScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("loadingScene.ts",loadingScene);
        reg("Game/MyGameScene.ts",MyGameScene);
        reg("Game/Fruit.ts",Fruit);
        reg("Game/Juice.ts",Juice);
    }
}
GameConfig.init();